
(() => {
"use strict";
const C=window.LINGKODPOS_CONFIG;
const db=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY);
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(Number(n)||0);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
let products=[],cart=new Map(),pollTimer=null,currentOrderId=null;

function toast(msg){const t=$("toast");t.textContent=msg;t.classList.remove("hidden");clearTimeout(t._t);t._t=setTimeout(()=>t.classList.add("hidden"),3000)}
function totals(){let subtotal=[...cart.values()].reduce((s,x)=>s+x.price*x.qty,0);let d=Math.min(Math.max(Number($("discount").value)||0,0),subtotal);return {subtotal,discount:d,total:subtotal-d}}
async function load(){const {data,error}=await db.from("products").select("id,name,price,stock,category").order("name");if(error){toast(error.message);return}products=data||[];renderProducts();renderCart()}
function renderProducts(){$("products").innerHTML=products.map(p=>`<button class="product" ${p.stock<1?"disabled":""} data-id="${p.id}"><div class="foodicon">🍽️</div><div class="pname">${esc(p.name)}</div><div class="price">${money(p.price)}</div><div class="stock">${p.stock>0?`Stock ${p.stock}`:"Out of stock"}</div></button>`).join("");document.querySelectorAll(".product").forEach(b=>b.onclick=()=>add(b.dataset.id))}
function add(id){const p=products.find(x=>x.id===id);if(!p)return;const x=cart.get(id)||{...p,qty:0};if(x.qty>=p.stock){toast("Not enough stock.");return}x.qty++;cart.set(id,x);renderCart()}
function change(id,n){const x=cart.get(id);if(!x)return;x.qty+=n;if(x.qty<=0)cart.delete(id);else cart.set(id,x);renderCart()}
function renderCart(){const arr=[...cart.values()];$("empty").classList.toggle("hidden",arr.length>0);$("cartitems").innerHTML=arr.map(x=>`<div class="cartrow"><div><b>${esc(x.name)}</b><br><span class="sub">${money(x.price)} × ${x.qty}</span></div><div class="qty"><button data-id="${x.id}" data-n="-1">−</button><b>${x.qty}</b><button data-id="${x.id}" data-n="1">+</button></div></div>`).join("");document.querySelectorAll(".qty button").forEach(b=>b.onclick=()=>change(b.dataset.id,Number(b.dataset.n)));const t=totals();$("subtotal").textContent=money(t.subtotal);$("discountView").textContent=money(t.discount);$("total").textContent=money(t.total)}
function items(){return [...cart.values()].map(x=>({product_id:x.id,quantity:x.qty}))}
async function callFn(name,body){const r=await fetch(`${C.SUPABASE_URL}/functions/v1/${name}`,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+C.SUPABASE_ANON_KEY,"apikey":C.SUPABASE_ANON_KEY},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Server request failed");return d}
async function cashSale(){const t=totals(),cash=Number($("cash").value);if(!cart.size)return toast("Add items first.");if(!Number.isFinite(cash)||cash<t.total)return toast("Insufficient cash.");try{const d=await callFn("create-cash-order",{items:items(),discount:t.discount,cash_received:cash});$("paymentArea").innerHTML=`<div class="status completed">PAID — Cash</div><p>Order #${d.order_number}</p><p>Change: <b>${money(d.change_amount)}</b></p><button class="btn ghost" id="newOrder">New order</button>`;$("newOrder").onclick=reset;clearInterval(pollTimer)}catch(e){toast(e.message)}}
async function gcash(){const t=totals();if(!cart.size)return toast("Add items first.");if(t.total<1)return toast("Minimum payment is ₱1.00.");$("gcashBtn").disabled=true;try{const d=await callFn("create-gcash-qr",{items:items(),discount:t.discount});currentOrderId=d.order_id;$("paymentArea").innerHTML=`<div class="status payment_processing">AWAITING GCash / QR Ph PAYMENT</div><div class="qrbox"><img src="${esc(d.qr_image)}" alt="Scan to pay"><p><b>Order #${d.order_number}</b></p><p>Amount: <b>${money(d.total)}</b></p><p class="ref">Scan this QR with GCash or another supported QR Ph app.</p></div><button class="btn danger" id="cancelPay">Cancel payment</button>`;$("cancelPay").onclick=()=>cancelPayment(currentOrderId);startPoll(currentOrderId)}catch(e){toast(e.message)}finally{$("gcashBtn").disabled=false}}
function startPoll(id){clearInterval(pollTimer);let attempts=0;pollTimer=setInterval(async()=>{attempts++;try{const d=await callFn("order-status",{order_id:id});if(d.status==="completed"){clearInterval(pollTimer);$("paymentArea").innerHTML=`<div class="status completed">PAID — GCash / QR Ph</div><p>Order #${d.order_number} confirmed.</p><p>Payment reference: ${esc(d.gcash_reference||"—")}</p><button class="btn ghost" id="newOrder">New order</button>`;$("newOrder").onclick=reset;await load()}else if(["payment_failed","voided","refunded"].includes(d.status)){clearInterval(pollTimer);$("paymentArea").innerHTML=`<div class="status ${d.status}">Payment ${d.status.replace("_"," ")}</div><button class="btn ghost" id="retry">Back to order</button>`;$("retry").onclick=()=>{$("paymentArea").innerHTML=""}}}catch(e){}if(attempts>900)clearInterval(pollTimer)},2000)}
async function cancelPayment(id){clearInterval(pollTimer);try{await callFn("cancel-gcash-order",{order_id:id});toast("Payment cancelled.");$("paymentArea").innerHTML="";currentOrderId=null;await load()}catch(e){toast(e.message)}}
function reset(){cart.clear();$("discount").value=0;$("cash").value="";$("cashPanel").classList.add("hidden");$("paymentArea").innerHTML="";currentOrderId=null;clearInterval(pollTimer);renderCart();load()}
$("showCash").onclick=()=>{$("cashPanel").classList.toggle("hidden");$("cash").focus()};$("cashBtn").onclick=cashSale;$("gcashBtn").onclick=gcash;$("discount").oninput=renderCart;load();
})();
